language: python
python:
    - "2.7"
before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
      - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      - chmod +x miniconda.sh
      - ./miniconda.sh -b
      - export PATH=/home/travis/miniconda/bin:$PATH
      - conda update --yes conda
      - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy==1.9.2 scipy==0.15.1 coveralls
install:
      - travis_retry pip install -r requirements_dev.txt
script:
    - PYTHONPATH=$PYTHONPATH:. coverage run --source server --rcfile=.coveragerc -m unittest discover tests
    - coverage combine
    - coverage report
after_success:
    coveralls --rcfile=.coveragerc
cache:
    - apt
    - directories:
        - $HOME/.cache/pip
